### PR TITLE
Docsify Documentation

### PR DESCRIPTION
**Pull request by rickiewars**
Following up on issue drogonframework/drogon#1460

This pull-request is ment to replace the abandoned Docsforge documentation.
This Docsify version can be hosted at Github Pages.

@an-tao mentioned that the pull-request must be compatible with the existing wiki.
If this is not the case, I would like some help, esspecially with the Chinese pages as I do not know Chinese.

Before this pull-request can be merged, I still need to remove the disclaimer which can be found on the home-page.
If possible, I would like to do that as late as possible because currently I also host it on my own Github-Pages site.

Some instructions for Github-Pages once the pull-request has been merged:
- Open the repo-settings and go to `Pages` under the `Code and automation` section
image
- Under `Source,` select `Deploy from a branch`
- Under `Branch` select the `master` branch and the `/ (root)` directory and press `save`
- Optionally, you could use your own domain like `docs.drogon.org`

Feedback is welcome, hope that this pull-request can be merged asap :)

### CODE REVIEW

**Comment by rickiewars** [comment]
Hi @an-tao,
I see you already merged the pull-request.
As mentioned in the pull-request, I still had a few temporary modifications telling that the repo was a fork and referencing to your repo's as original one.
Are you going to correct those changes yourself or do you want me to create a new pull request correcting these changes?

Thanks for accepting my contribution

**Comment by an-tao** [comment]
@rickiewars Thanks so much for your help.  
I want to see the effect as soon as possible so I merged it in advance, I would be very grateful if you would do the fixes you mentioned.

**Comment by an-tao** [comment]
@rickiewars In addition, I think pages can completely replace the wiki, you don't have to make your modifications compatible with the wiki, I can maintain a wiki branch myself. thanks so much.

**Comment by rickiewars** [comment]
I created a pull-request at #58

**Comment by rickiewars** [comment]
Glad I could make this contribution :)

**Comment by an-tao** [comment]
BTW: Can Docsify generate docs from the public headers via Doxygen? That's a part of the Docsforge.

**Comment by rickiewars** [comment]
How do you mean exactly?

**Comment by an-tao** [comment]
> How do you mean exactly?

I wrote a lot of comments in the public header files including special tags for [Doxygen](https://www.doxygen.nl/). the Docsforge uses Doxygen and the wiki repository to generate the drogon documentations page, can Docsify do the same thing?

**Comment by rickiewars** [comment]
Ah doxygen, i was confused due to the many "docs" names.
I searched a bit around in the Docsify repo's but couldn't find any reference to Doxygen unfortunately.

You could add URL references to the corosponding doxygen pages manualy and host the generated doxygen site seperately with e.g. github pages but that would take a bit more work.

You can however easily extend docsify using Javascript and many js extensions are already available so maybe if you can think of an easy relationship between doxygen and the markdown docs, you could write a plugin yourself.

**Comment by an-tao** [comment]
@rickiewars 
Hi, thanks so much for your help, I merged 

> Ah doxygen, i was confused due to the many "docs" names. I searched a bit around in the Docsify repo's but couldn't find any reference to Doxygen unfortunately.
> 
> You could add URL references to the corosponding doxygen pages manualy and host the generated doxygen site seperately with e.g. github pages but that would take a bit more work.
> 
> You can however easily extend docsify using Javascript and many js extensions are already available so maybe if you can think of an easy relationship between doxygen and the markdown docs, you could write a plugin yourself.

Thanks so much.

**Comment by rbugajewski** [comment]
In this case I think we should generate a separate page with a HTML version of the Doxygen documentation in our project, and make a more prominent link in the updated documentation.

This would be a great first step, until we find a better way to integrate both parts of the documentation.

Thanks for your contribution.

**Pull request merged**
